---
capturing_device:
  type: local_camera_cv2
  connection:
    device_id: 0
  parameters:
    CAP_PROP_FRAME_HEIGHT: 1280
    CAP_PROP_FRAME_WIDTH: 720
    CAP_PROP_FPS: 30
  capturing_interval: 1000
data_storage:
  type: local
  connection:
    filepath: /var/data/vision/
    filename_mask: image_
buffer:
  max_size: 100
influxdb:
  host: 127.0.0.1
  port: 8086
  user: root
  password: root
  database: CV
  db_user: db_user
  db_password: db_password
  reconnect_interval: 10000
  write_interval: 10000
  metric_id: flow_regime, camera top
  measurement: flow_regime
metadata:
  '010F': RaspPi
  '0110': HQ Camera v1.1
  '0112': 1
  '829D': 1.0
event_logger:
  publish: false
  print_level: DEBUG
