---
inlets:
  1:
    name: camera
    type: local_camera_cv2
    hidden: False
    parameters:
      device_id: 0
      Width: 720
      ExposureTime: 720
    metadata:
      '010F': Raspberry Pi # Manufacturer of recording equipment
  2:
    name: light_conditions
    type: static_variable
    hidden: False
    parameters:
      value: natural
    metadata:
      unit: none
      interpretation: no artificial light switched on
      description: light conditions during experiment
processors:
  0:
    name: image_input
    type: input
    input_inlets:
      - all
  1:
    name: resize
    type: image_resize
    hidden: False
    parameters:
      width: 250
      height: 250
      interpolation: INTER_NEAREST
  2:
    name: saver
    type: save_on_disk
    parameters:
      save_path: '../data'
shell:
  type: rest_api
  parameters:
    host: 0.0.0.0
    port: 5000
    endpoint: '/get_frame'