---
inlets:
  1:
    name: camera
    type: baumer_camera_neoapi
    hidden: False
    parameters:
      device_id: 0
      Width: 720
      ExposureTime: 720
    metadata:
      '010F': Raspberry Pi # Manufacturer of recording equipment
      '0110': HQ Camera v1.1 # The model name or model number of the equipment
  2:
    name: light_conditions
    type: static_variable
    hidden: False
    parameters:
      value: natural
    metadata:
      unit: none
      interpretation: no artificial light switched on
      description: light conditions during experiment
  3:
    name: flow_regime
    type: static_variable
    hidden: False
    parameters:
      value: 0
    metadata:
      unit: none
      interpretation: flooded
      description: flow regime in reactor
processors:
  0:
    name: image_input
    type: input
    input_inlets:
      - camera
  1:
    name: resize
    type: image_resize
    hidden: True
    parameters:
      width: 250
      height: 250
      interpolation: INTER_NEAREST
  2:
    name: crop
    type: image_crop
    hidden: False
    parameters:
      x_init: 2
      x_diff: 248
      y_init: 2
      y_diff: 248
shell:
  type: rest_api
  parameters:
    host: 0.0.0.0
    port: 5000
    endpoint: '/get_frame'