name: Build and Publish

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check tag
      run: echo 'Version acoording to tag is ${GITHUB_REF##*/}'
    - name: Update version tag
      run: echo "__version__ = '${GITHUB_REF##*/}'" > ./src/planteye_vision/__init__.py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build
      run: |
        python -m build
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository pypi dist/*
